name: RAPx CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  latest:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup toolchain
      run: |
        rustup toolchain install nightly --profile minimal
        rustup component add rustc-dev rust-src llvm-tools-preview rustfmt --toolchain nightly
        rustup override set nightly
        rustc --version
    - name: Build
      run: ./install.sh
    - name: Test
      run: cd rapx && cargo test

  asterinas:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup toolchain
      run: |
        rustup toolchain install nightly-2026-04-03 --profile minimal
        rustup component add rustc-dev rust-src llvm-tools-preview rustfmt --toolchain nightly-2026-04-03
        rustup override set nightly-2026-04-03
        rustc --version
    - name: Build
      run: ./install.sh
    - name: Test
      run: cd rapx && cargo test

  verify-std:
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - name: Setup toolchain
      run: |
        rustup toolchain install nightly-2025-10-09 --profile minimal
        rustup component add rustc-dev rust-src llvm-tools-preview rustfmt --toolchain nightly-2025-10-09
        rustup override set nightly-2025-10-09
        rustc --version
    - name: Build
      run: ./install.sh
    - name: Test
      run: cd rapx && cargo test
