name: RAPx-booting and testing

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RAP_RECURSIVE: deep

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rust:
          - pinned
          - latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup asterinas (via rust-toolchain.toml)
      if: matrix.rust == 'pinned'
      run: rustup show active-toolchain

    - name: Setup latest nightly
      if: matrix.rust == 'latest'
      run: |
        rustup toolchain install nightly --profile minimal
        rustup component add rustc-dev rust-src llvm-tools-preview rustfmt --toolchain nightly
        rustup override set nightly

    - name: Build RAPx
      run: ./install.sh

    - name: Running Cargo Test
      run: cd rapx && cargo test

  verify-std:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Setup nightly-2025-10-09 for verify-std
      run: |
        rustup toolchain install nightly-2025-10-09 --profile minimal
        rustup component add rustc-dev rust-src llvm-tools-preview rustfmt --toolchain nightly-2025-10-09
        rustup override set nightly-2025-10-09

    - name: Build RAPx
      run: ./install.sh

    - name: Running Cargo Test (verify-std)
      run: cd rapx && cargo test
